### ISSUE TITLE
multiple Cognito User Pool Client support

### ISSUE THREAD

**Issue by bgdsh** [Perpherior/sls_hub#14]
https://github.com/DevHubCo/sls_hub/blob/master/lib/serverless_hub/authorizer.rb#L36 
Hi, as shown in the code above, after keys fetched from the AWS side, only the first key used to verify the token.
If I have multiple clients and this token is not generated by the first client, the token verification will fail.

The suggested solution is: 
- decode the token without verifying firstly to know which key this access token is using
- get the right key by id from the key set.
- do the verification.

**Comment by lumicore-max** [comment]
Closing now.
